### ISSUE TITLE
1.5 Configuring Routes: Cannot GET /contacts

### ISSUE THREAD

**Issue by skube** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#10]
I get the following result when attempting to view the Contacts route. 

    Cannot GET /contacts

There are no errors in the console. Most likely I've probably made some silly mistake but I've been scratching my head for a while now.

**update**: I noticed that if I change the URI to `http://localhost:3000/#/contacts` it _will_ work. It will remove the `#/` automatically and appear to redirect to `http://localhost:3000/contacts`. However going to that URI *directly* does not work.

**Comment by adamarthurryan** [comment]
Hi Skube,

Have you tried running the final project from the repository? Does that work correctly?

---

Adam Brown
Code Course Editor
Tuts+

**Comment by shaohaolin** [comment]
@skube  can you post your api.js and main.html code here?

**Comment by skube** [comment]
Thanks but it's been so long and I don't have it any more. If this was just me I probably did something incorrectly. I'll close this for now.
