### ISSUE TITLE
explicitly specify "extended: true" for extended parsing accounts.js

### ISSUE THREAD

**Issue by KiranKumarAlugonda** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#13]
In account.js file, we have to replace the  :    `.use(bodyParser.urlencoded())`
with     `.use(bodyParser.urlencoded({extended :true})) `, as it requires  the extended parameter to be mentioned explicitly.

**Comment by adamarthurryan** [comment]
@andrew8088 - should we update this in the source code?

**Comment by andrew8088** [comment]
@adamarthurryan yes, let's do that.

**Comment by adamarthurryan** [comment]
Ah, looks like it made it in from the last pull request.
