### ISSUE TITLE
On step 2.3 - Token '{' invalid key at column 2

### ISSUE THREAD

**Issue by devepman** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#15]
I have the exact same code (verified several times) as you have in the video and its not working for me. Im on step 2.3 form field directives - the directive.

Im getting following error:

In the browser:

Error: [$parse:syntax] http://errors.angularjs.org/1.4.1/$parse/syntax?p0=%7B&p1=invalid%20key&p2=2&p3=%7B%7Bfield%7D%7D.%24error&p4=%7Bfield%7D%7D.%24error
On angular site:

Error: $parse:syntax Syntax Error Syntax Error: Token '{' invalid key at column 2 of the expression [{{field}}.$error] starting at [{field}}.$error].

I asked a experienced coder and he said you're using bad practice in this project and expressions shouldnt be used like that in directives. When I tried to change from {{form}}.*\* to form.**, I didnt manage to get it to work either. Please help.

**Comment by andrew8088** [comment]
Yes, that directive was a little hacky. Sorry about that.

Other people have has this problem; the issue is that newer versions of many the packages used in this project have broken things. The solution is to install the older versions of the packages. Here's a `bower.json` file that should work for you:

```
{
    "name": "Contacts App", 
    "version": "1.0.0", 
    "license": "MIT", 
    "dependencies": {
        "angular-messages": "1.3.0-build.3024+sha.60c13a1", 
        "angular-resource": "1.2.21", 
        "angular-route": "1.2.21", 
        "angular": "1.3.0-build.3024+sha.60c13a1", 
        "bootstrap": "3.2.0", 
        "jquery": "2.1.1"
    }
}
```

Put that in place and run `bower install`; once you have the right packages, things should work.

**Comment by devepman** [comment]
I made bower.json file in the root and placed that text. It then installed and asked me:

Prefix the choice with ! to persist it to bower.json

Unable to find a suitable version for angular, please choose one:
    1) angular#1.2.21 which resolved to 1.2.21 and is required by angular-resource#1.2.21, angular-route#1.2.21
    2) angular#1.3.0-build.3024+sha.60c13a1 which resolved to 1.3.0-build.3024+sha.60c13a1 and is required by angular-messages#1.3.0-build.3024+sha.60c13a1, Contacts App
    3) angular#1.4.1 which resolved to 1.4.1 and is required by angular-resource#1.4.1
    4) angular#1.4.2 which resolved to 1.4.2 and is required by angular-messages#1.4.2

I chose 4.

It installed but now Im getting a different issue:
Error: $parse:syntax
Syntax Error
Syntax Error: Token '' {1} at column {2} of the expression [{3}] starting at [{4}].

**Comment by andrew8088** [comment]
This project was build with Angular 1.3, so you'll have to choose 2. Delete your `public/lib` (or wherever you keep your bower components) directory (just to be safe) and run `bower install` again.

**Comment by devepman** [comment]
Thanks for that! I did that and now it works fine to create a new contact but not to see the contacts.. Strange!

I get this error message:
Error: [$injector:unpr] Unknown provider: optionsProvider <- options
http://errors.angularjs.org/1.3.0-build.3024+sha.60c13a1/$injector/unpr?p0=optionsProvider%20%3C-"<div class="col-sm-12 ng-scope" ng-view="">"ptions

from Angular site:
Error: $injector:unpr
Unknown Provider
Unknown provider: optionsProvider
Description
This error results from the $injector being unable to resolve a required dependency. To fix this, make sure the dependency is defined and spelled correctly. For example:

angular.module('myApp', [])
.controller('MyController', ['myService', function (myService) {
  // Do something with myService
}]);

Do you know why it might be? Thanks!

**Comment by andrew8088** [comment]
Looks like you might have an error in the optionsProvider. If you email me the code, I can find something more specific.

**Comment by mfonsos** [comment]
Hello,

I am trying to build the contact_app as a module to a wider project and i cannot just install older versions of the packages. Is there a solution to newer versions...can you please point on how can we overcome this error;

Thank you again for this great tutorial...looking forward.

## updated

what i did to overcome the problem...i had installed "angular-messages": "~1.4.4" which i changed to version "angular-messages": "1.3.0-build.3024+sha.60c13a1" as you suggested.

I bower install again and now it works fine...i am working with angular version 1.3.15.

Thanks

**Comment by andrew8088** [comment]
@mfonsos That's great!
