### ISSUE TITLE
router. dot issue in api.js

### ISSUE THREAD

**Issue by iphoneuser** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#5]
In api.js you have instructed to write: (line 25) [lecture 1.6]
router.
    .param('id', function (req, res, next) 

but my node server is throwing exception for that.   Can you please provide source codes of the project in the stage after lecture 1.7?

**Comment by NovozhiloffVadim** [comment]
Delete that dot after router so this piece of code looks like this:    
    `router`
        `.param('id', function (req, res, next) {`
            `req.dbQuery = { id: parseInt(req.params.id, 10) };`
           ` next();`
       ` })`
