### ISSUE TITLE
issues with the query on the contact list

### ISSUE THREAD

**Issue by AKFourSeven** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#7]
Hi I was working with the tutorial until the lesson 7 and when I tried doing a search it would simply not work.
Though I haven't changed a thing from the code written up to that point.
It seems that whenever a search is launched I get a blank list.
The list is filtered by query and I called ng-model="query" on the search field.

Any help would be much appreciated.

thanks

**Comment by magalhini** [comment]
Same issue here... no contacts displayed at all. Logging the output of the `Contacts.query()` method gives me an unresolved promise with a length of 0, and nothing else seems to be happening... anyone has any ideas?

**Comment by magalhini** [comment]
Ah, finally I've found the issue!

Turns out what's missing is a call to the `next()` function on the middleware, hence why it was hanging in-between the query.

So, at that stage (lesson 7), you can add the call on the middleware like so:

```js
router
    .use(function(req, res, next) {
        if (!req.user) { req.user = {id: 1}; }
        next();
    })
```
And that should get things going!
