### ISSUE TITLE
PUT http://localhost:3000/api/contact 404 (Not Found)

### ISSUE THREAD

**Issue by Shijir** [tutsplus/Building-a-Web-App-From-Scratch-With-AngularJS#8]
I am getting this error when I click on the remove button of the fields:
PUT http://localhost:3000/api/contact 404 (Not Found)

I thought I did something wrong in the code  so I cloned the repository and started the server but I am still getting the same error.

What could be causing this error?

**Comment by adamarthurryan** [comment]
Do other parts of the site work properly? Do you see successful GET/PUT requests on the console log from your NodeJS server?

**Comment by andrew8088** [comment]
The URL is http://localhost:3000/api/contacts (contacts, plural), I think. Also, when using PUT, you should have /:id at the end of that.

**Comment by voanhtuan8881** [comment]
http://localhost:3000/api/contacts
